# Generated by Django 2.2.3 on 2019-07-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulation',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
