# Generated by Django 2.2.3 on 2019-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=20, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('issued_to', models.CharField(blank=True, max_length=20)),
                ('issue_date', models.DateField(blank=True, default='2019-01-01')),
            ],
        ),
    ]
