# Generated by Django 2.2.3 on 2019-07-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190710_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulation',
            name='issue_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
