# Generated by Django 2.2.3 on 2019-07-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190710_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulation',
            name='return_date',
            field=models.DateField(blank=True, default='2019-01-01'),
            preserve_default=False,
        ),
    ]
